// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SampleCore.Entity
{
    public partial class Student_Details
    {
        public int Student_ID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Department { get; set; }
        public int Age { get; set; }
        public string Class { get; set; }
        public string Gender { get; set; }
        public DateTime Year_Of_Joining { get; set; }
        public string Phone { get; set; }
        public string Location { get; set; }
        public bool Is_Deleted { get; set; }
        public DateTime Created_Time_Stamp { get; set; }
        public DateTime Updated_Time_Stamp { get; set; }
    }
}